### ISSUE TITLE
advanced margin engine: should not remove collateral if the vault contains expired short

### ISSUE THREAD

**Issue by antoncoding** [antoncoding/grappa#109]

**Comment by antoncoding** [comment]
@kjr217 This only affects the advanced margin because it lets you settle with less collateral you're supposed to have for payout.

In `FullMargin`, if you only remove collateral it will revert because of the collat rule, and if you remove + settle it also reverts because you don't have enough collateral to deduct payout from

**Comment by kjr217** [comment]
yeah makes sense
