### ISSUE TITLE
cicd: publish npm packages for import

### ISSUE THREAD

**Issue by antoncoding** [antoncoding/grappa#119]
* try importing from foundry project with gitmodule
* try publish npm package
* try importing from hardhat project

**Comment by antoncoding** [comment]
Also would be most helpful to publish library for util functions
https://github.com/antoncoding/grappa/blob/master/src/test/shared/ActionHelper.sol#L11

**Comment by dsshap** [comment]
> Also would be most helpful to publish library for util functions https://github.com/antoncoding/grappa/blob/master/src/test/shared/ActionHelper.sol#L11

`getTokenId` fits nicely into `TokenIdUtil` [PR122](https://github.com/antoncoding/grappa/pull/122/files#diff-80f84c61f60b90af9789d0ee6c971cc86f4139a8276a68043186662fd84cdaa1)

Creating an `ActionsUtil` makes sense to house the rest.
