### ISSUE TITLE
feature: Accounts to support minting/holding multiple options.

### ISSUE THREAD

**Issue by dsshap** [antoncoding/grappa#133]
An account should be able to mint any number of calls/puts.
An account should be able to hold any number of calls/puts.
An account should be able to hold any number of collaterals.

**Comment by antoncoding** [comment]
what do you think the best way to calculate collateral is?
if you have a data structure such as:

```
short (minted) : [1x 1200 call, 2x 1500 call]
long (minted) : [1x 1300 call, 2x 800 put, 2x 1700 call]
collateral: [1 eth, 500 usd]
```

**Comment by dsshap** [comment]
I imagined a data structure like this:

```
shortCalls mapping(uint256 tokenId => uint64 amount)
shortPuts mapping(uint256 tokenId => uint64 amount)
longCalls mapping(uint256 tokenId => uint64 amount)
longPuts mapping(uint256 tokenId => uint64 amount)
collateral mapping(collateralId => uint80 amount) 
``` 
* Probably using EnumerableMap for convenience.

Then iterate over the shorts, comparing them with longs that match the underlying and expiry (at least in the first iteration).
