### ISSUE TITLE
add NFT tokenDescriptor

### ISSUE THREAD

**Issue by antoncoding** [antoncoding/grappa#150]
Add contract to return url for NFT. Can make the actual contract later

**Comment by dsshap** [comment]
what tis this?

**Comment by antoncoding** [comment]
we can plugin a contract to return a cooler NFT for our 1155 OptionToken.
Kind of like Uniswap's NFT: https://docs.uniswap.org/protocol/reference/periphery/interfaces/INonfungibleTokenPositionDescriptor

**Comment by antoncoding** [comment]
it only affect the "view url" function, which determine how it's shown in your wallet ..etc. So don't have concern about security. Can definitely be done later. 
Right now we just need to plug that contract into OptionToken's constructor so that it can read from it in the future.
